### ISSUE TITLE
Warning window "unusually high transaction fee"

### ISSUE THREAD

**Issue by rmrm-rami** [Feathercoin-Foundation/electrum-ftc#14]
Thresholds for "high tx fees" from Bitcoin-Electrum haven't been adjusted for Feathercoin when sending a transaction. The warning window appears also if the minimum fee is selected.

![image](https://user-images.githubusercontent.com/37974898/38171727-bbb6c6da-359f-11e8-8d85-182cfb517d85.png)

Also, the fee bar, except for the highest fee, says "1000. sat/byte", even though the expected confirmation time goes from 25 blocks down to 2 blocks. This is somewhat misleading.

e.g. lowest fee:
![image](https://user-images.githubusercontent.com/37974898/38171748-1083175e-35a0-11e8-9a3c-ec54cd36b518.png)

second-highest fee:
![image](https://user-images.githubusercontent.com/37974898/38171754-21367046-35a0-11e8-9870-dd571b960490.png)

**Comment by toxeus** [comment]
[Here's](https://github.com/Feathercoin-Foundation/electrum-ftc/blob/9bfa9c69428935e9bce7430415583b6444d7d9df/gui/qt/main_window.py#L1365-L1367) the code that triggeres this warning. Looks like [MAX_FEE_RATE](https://github.com/Feathercoin-Foundation/electrum-ftc/blob/9bfa9c69428935e9bce7430415583b6444d7d9df/lib/bitcoin.py#L106) needs to be tuned.

**Comment by lclc** [comment]
I removed the warning for 3.0.6 for now in commit: https://github.com/Feathercoin-Foundation/electrum-ftc/commit/019e1e9a34901a41f2e5bdc9c0087dd7514e3721

Since Feathercoin nodes have a higher minimum relay fee we don't want to
warn if there is a higher transaction fee. The amount in dollar is still
very low. This probably should be added back in version 3.1.
