### ISSUE TITLE
Addresses Tab -> Sign/Verify -> Signature Field should be non editable

### ISSUE THREAD

**Issue by Anilkumar18** [Feathercoin-Foundation/electrum-ftc#61]
## Expected Behavior
Addresses Tab -> Sign/Verify -> Signature Field should be non editable

## Current Behavior
Addresses Tab -> Sign/Verify -> Signature Field is editable

## Steps to Reproduce
1.Open a wallet
2.Go to addresses tab,right click on a particular address and select Sign/Verify in the pop up
3.Type anything in to the message field and click Sign,the user would be able to edit the auto generated signature
4.The field should be non editable and user should only be allowed to copy from it

## Context
If the User by mistake edits/delete a existing signature, he might have to regenerate it

## Your Environment
* Version used: Electrum FTC 3.0.6.5
* Operating System and version: Windows 10

**Comment by lclc** [comment]
The signature has to be editable because of the "Verify" use-case:
Someone sends me an address, the message and the signatures to proof he owns that address.
E.g.:
My message: This is the address of Lucas Betschart
My address: fc1qhpffx6t6wjq8lukh9pv7kngv4fgd6ca0tgslty
My signature: IClGEZEP4yWGJIwQAg9Ny2+hXJ9+MlgRlBjncc3iDsC8bTh6kHvIXJwC0qjh/LLjkCkzOpE8ivER5JFofDEi0Gw=

Now you can add all those 3 and Verify it in your client.
