### ISSUE TITLE
Addresses Tab ->Encrypt/Decrypt -> Clicking on Decrypt button does not show any change in the screen

### ISSUE THREAD

**Issue by Anilkumar18** [Feathercoin-Foundation/electrum-ftc#65]
## Expected Behavior
Addresses Tab ->Encrypt/Decrypt -> Clicking on Decrypt button should display a message "message decrypted" or atleast allow user to copy it to a text file

## Current Behavior
Addresses Tab ->Encrypt/Decrypt -> Clicking on Decrypt button does not show any change in the screen

## Steps to Reproduce
1.Open a wallet
2.Go to addresses tab,right click on a particular address and select encrypt/decrypt in the pop up
3.In the encrypt/decrypt window enter text in message text field  and click on Encrypt
4.Encrypted message is automatically generated and displayed in the field
5.Now click on Decrypt
6.There is no changes in the screen

## Context
Currently user has no idea if the message has been decrypted or not.

## Your Environment

* Version used: Electrum FTC 3.0.6
* Operating System and version: Windows 10

Note : Issue exists in Bitcoin also

**Comment by lclc** [comment]
If you enter the text you want to have encrypted (in "Message"), encrypt it and then use the same encrypted input (in "Encrypted" field) again to Decrypt it shouldn't change the message above (since the input was the same). So that's the expected behaviour.


Maybe the UI could be improved to make the Encrypt/Decrypt as well as the Sign/Verify dialog always work in both directions.
